### PR TITLE
Add document validation for Ruby code

### LINKED ISSUE #8: Add document validation for Ruby code
The Ruby console app needs to validate the input document. Please follow validation rules from [documentation](https://github.com/dmodena/polyglot-registration/blob/main/src/README.md).

### PR DESCRIPTION
**Pull request by sharkham**
**Description**

- Adds document validation for Ruby code

**Related issue(s)**
Resolves #8

### CODE REVIEW

**Comment by sharkham** [comment]
As far as I can tell, the test that's failed is the email validation test, and that isn't what this PR was to resolve? Please let me know if I'm missing something though!

**Comment by dmodena** [comment]
Thank you so much for your contribution! The tests are passing for the document validation, so it is all good.

**Comment by dmodena** [comment]
@all-contributors please add @sharkham for contribution to code.

**Comment by sharkham** [comment]
Thanks @dmodena ! And sounds good about the tests :)

**Pull request merged**
